name: "Service Checks"

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check_services:
    runs-on: ubuntu-latest
    steps:
      - name: Check Endpoints
        run: |
          ENDPOINTS=(
            "http://a24e9437d0d90466cadddf2a054451d0-1266191092.us-east-1.elb.amazonaws.com/"
          )
          for endpoint in "${ENDPOINTS[@]}"; do
            echo "Checking $endpoint"
            status_code=$(curl -o /dev/null -s -w "%{http_code}" "$endpoint")
            if [ "$status_code" -ne 200 ]; then
              echo "❌ Error: $endpoint returned status code $status_code"
              exit 1
            else
              echo "✅ Success: $endpoint is up."
            fi
          done

      - name: "Send Slack Notification"
        if: failure()
        uses: felleslosninger/github-actions/send-slack-notification@v0.2.2
        with:
          slack-channel-id: "your-slack-channel-id"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}