#name: "Service Checks"
#
#on:
#  schedule:
#    - cron: '*/5 * * * *'
#
#jobs:
#  check_services:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check Endpoints
#        run: |
#          ENDPOINTS=(
#            "https://example.com/api1"
#            "https://example.com/api2"
#            "https://example.com/api3"
#          )
#          for endpoint in "${ENDPOINTS[@]}"; do
#            echo "Checking $endpoint"
#            status_code=$(curl -o /dev/null -s -w "%{http_code}" "$endpoint")
#            if [ "$status_code" -ne 200 ]; then
#              echo "❌ Error: $endpoint returned status code $status_code"
#              exit 1
#            else
#              echo "✅ Success: $endpoint is up."
#            fi
#          done
#
#      - name: "Send Slack Notification"
#        if: failure()
#        uses: felleslosninger/github-actions/send-slack-notification@v0.2.2
#        with:
#          slack-channel-id: "your-slack-channel-id"
#          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}